/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zhscript_Jni */

#ifndef _Included_org_zhscript_Jni
#define _Included_org_zhscript_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zhscript_Jni
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/zhscript/Jni;Landroid/content/res/AssetManager;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zhscript_Jni_init
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject, jstring);

/*
 * Class:     org_zhscript_Jni
 * Method:    jieshi
 * Signature: ([Ljava/lang/String;Lorg/zhscript/Result;Lorg/zhscript/Jni;)I
 */
JNIEXPORT jint JNICALL Java_org_zhscript_Jni_jieshi
  (JNIEnv *, jobject, jobjectArray, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
