
if(argc <= 0) {
	if(!ret) {
		typedef void (*func___)();
		((func___)func)();
		return 0;
	}
	typedef unsigned long int (*func___)();
	return ((func___)func)();
}
if(!ret) {
	typedef void (*func___)(...);
switch(argc) {
case 1:
	((func___)func)(argv[0]);
	break;
case 2:
	((func___)func)(argv[0], argv[1]);
	break;
case 3:
	((func___)func)(argv[0], argv[1], argv[2]);
	break;
case 4:
	((func___)func)(argv[0], argv[1], argv[2], argv[3]);
	break;
case 5:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4]);
	break;
case 6:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5]);
	break;
case 7:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6]);
	break;
case 8:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7]);
	break;
case 9:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8]);
	break;
case 10:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9]);
	break;
case 11:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10]);
	break;
case 12:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11]);
	break;
case 13:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11], argv[12]);
	break;
case 14:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11], argv[12], argv[13]);
	break;
case 15:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11], argv[12], argv[13], argv[14]);
	break;
case 16:
	((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11], argv[12], argv[13], argv[14], argv[15]);
	break;
}
	return 0;
}
typedef unsigned long int (*func___)(...);
switch(argc) {
case 1:
	return ((func___)func)(argv[0]);
case 2:
	return ((func___)func)(argv[0], argv[1]);
case 3:
	return ((func___)func)(argv[0], argv[1], argv[2]);
case 4:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3]);
case 5:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4]);
case 6:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5]);
case 7:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6]);
case 8:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7]);
case 9:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8]);
case 10:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9]);
case 11:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10]);
case 12:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11]);
case 13:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11], argv[12]);
case 14:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11], argv[12], argv[13]);
case 15:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11], argv[12], argv[13], argv[14]);
case 16:
	return ((func___)func)(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], argv[9], argv[10], argv[11], argv[12], argv[13], argv[14], argv[15]);
}
